name: CapturePointClaims
version: ${project.version}
#website:
author: RoboMWM
main: com.robomwm.CapturePointClaims.CapturePointClaims
depend:
- GrandioseAPI
- BetterTPA
- SimpleClans
softdepend:
- Multiverse-Core
commands:
  tppoint:
    aliases: [tpclaim, tppost]
