name: CapturePointClaims
version: ${project.version}
#website:
author: RoboMWM
main: com.robomwm.CapturePointClaims.CapturePointClaims
api-version: 1.13
depend:
- GrandioseAPI
- BetterTPA
- SimpleClans
softdepend:
- Multiverse-Core
- dynmap
commands:
  tppost:
    aliases: [tpppoint, tpclaim, tppoint, tpppost, cp, tpcp, claimpoint, claimpoints, capturepoints, cpaturepiont, capturepoint]
