name: CapturePointClaims
version: ${project.version}
#website:
author: RoboMWM
main: com.robomwm.CapturePointClaims.CapturePointClaims
softdepend:
- Multiverse-Core
- SimpleClans
- BetterTPA
commands:
  tppoint:
    aliases: [tpclaim]
